// samples/next.js/app/page.tsx
'use client';

import { Post } from '@/zenstack/models';
import { schema } from '@/zenstack/schema-lite';
import { FetchFn, useClientQueries } from '@zenstackhq/tanstack-query/react';
import { LoremIpsum } from 'lorem-ipsum';
import Image from 'next/image';
import { useState } from 'react';

const lorem = new LoremIpsum({ wordsPerSentence: { max: 6, min: 4 } });

export default function Home() {
    const [showPublishedOnly, setShowPublishedOnly] = useState(false);
    const [enableFetch, setEnableFetch] = useState(true);
    const [optimistic, setOptimistic] = useState(false);

    const fetch: FetchFn = async (url, init) => {
        // simulate a delay for showing optimistic update effect
        await new Promise((resolve) => setTimeout(resolve, 1000));
        return globalThis.fetch(url, init);
    };

    const clientQueries = useClientQueries(schema, { fetch });
    const { data: users, isFetched: isUsersFetched } = clientQueries.user.useFindMany();

    const { data: posts } = clientQueries.post.useFindMany(
        {
            where: showPublishedOnly ? { published: true } : undefined,
            orderBy: { createdAt: 'desc' },
            include: { author: true },
        },
        { enabled: enableFetch },
    );

    const createPost = clientQueries.post.useCreate({ optimisticUpdate: optimistic });
    const deletePost = clientQueries.post.useDelete({ optimisticUpdate: optimistic });
    const updatePost = clientQueries.post.useUpdate({ optimisticUpdate: optimistic });

    const onCreatePost = () => {
        if (!users) {
            return;
        }

        // random title
        const title = lorem.generateWords();

        // random user as author
        const forUser = users[Math.floor(Math.random() * users.length)];

        console.log('Creating post for user:', forUser.id, 'with title:', title);
        createPost.mutate({
            data: {
                title,
                authorId: forUser.id,
            },
        });
    };

    const onDeletePost = (postId: string) => {
        deletePost.mutate({
            where: { id: postId },
        });
    };

    const onTogglePublishPost = (post: Post) => {
        updatePost.mutate({
            where: { id: post.id },
            data: { published: !post.published },
        });
    };

    if (isUsersFetched && (!users || users.length === 0)) {
        return <div className="p-4">No users found. Please run &quot;pnpm db:init&quot; to seed the database.</div>;
    }

    return (
        <div className="flex min-h-screen items-center justify-center bg-zinc-50 font-sans dark:bg-black">
            <main className="flex min-h-screen w-full max-w-3xl flex-col items-center py-32 px-16 bg-white dark:bg-black sm:items-start">
                <Image className="dark:invert" src="/next.svg" alt="Next.js logo" width={100} height={20} priority />
                <div className="flex flex-col mt-16 items-center gap-6 text-center sm:items-start sm:text-left">
                    <h1 className="max-w-xs text-3xl font-semibold leading-10 tracking-tight text-black dark:text-zinc-50">
                        My Awesome Blog
                    </h1>

                    <button
                        onClick={onCreatePost}
                        className="rounded-md bg-blue-600 px-4 py-2 text-white hover:bg-blue-700 cursor-pointer"
                    >
                        New Post
                    </button>

                    <div>
                        <div>Current users</div>
                        <div className="flex flex-col gap-1 p-2">
                            {users?.map((user) => (
                                <div key={user.id} className="text-sm text-gray-500">
                                    {user.email}
                                </div>
                            ))}
                        </div>
                    </div>

                    <div className="flex flex-col gap-1">
                        <label className="text-sm text-gray-700 dark:text-gray-300">
                            <input
                                type="checkbox"
                                checked={showPublishedOnly}
                                onChange={(e) => setShowPublishedOnly(e.target.checked)}
                                className="mr-2"
                            />
                            Show published only
                        </label>

                        <label className="text-sm text-gray-700 dark:text-gray-300">
                            <input
                                type="checkbox"
                                checked={enableFetch}
                                onChange={(e) => setEnableFetch(e.target.checked)}
                                className="mr-2"
                            />
                            Enable fetch
                        </label>

                        <label className="text-sm text-gray-700 dark:text-gray-300">
                            <input
                                type="checkbox"
                                checked={optimistic}
                                onChange={(e) => setOptimistic(e.target.checked)}
                                className="mr-2"
                            />
                            Optimistic update
                        </label>
                    </div>

                    <ul className="flex flex-col gap-2 container">
                        {posts?.map((post) => (
                            <li key={post.id}>
                                <div className="flex justify-between">
                                    <div className="flex gap-2 items-baseline">
                                        <h2 className="text-xl font-semibold">{post.title}</h2>
                                        {post.$optimistic ? <span className="text-sm">pending</span> : null}
                                    </div>
                                    <div className="ml-4 flex w-32">
                                        <button
                                            className="rounded-md px-2 py-1 text-white cursor-pointer underline text-xs"
                                            onClick={() => onDeletePost(post.id)}
                                        >
                                            Delete
                                        </button>
                                        <button
                                            className="rounded-md px-2 py-1 text-white cursor-pointer underline text-xs"
                                            onClick={() => onTogglePublishPost(post)}
                                        >
                                            {post.published ? 'Unpublish' : 'Publish'}
                                        </button>
                                    </div>
                                </div>
                                {post.$optimistic ? null : (
                                    <p className="text-sm text-gray-500">
                                        by {post.author.name} {!post.published ? '(Draft)' : ''}
                                    </p>
                                )}
                            </li>
                        ))}
                    </ul>
                </div>
            </main>
        </div>
    );
}

// samples/nuxt/app/app.vue
<script setup lang="ts">
import { useClientQueries, type FetchFn } from '@zenstackhq/tanstack-query/vue';
import { LoremIpsum } from 'lorem-ipsum';
import { ref } from 'vue';
import type { Post } from '~~/zenstack/models';
import { schema } from '~~/zenstack/schema-lite';

const lorem = new LoremIpsum({ wordsPerSentence: { max: 6, min: 4 } });

const showPublishedOnly = ref(false);
const enableFetch = ref(true);
const optimistic = ref(false);

const fetch: FetchFn = async (url, init) => {
    // simulate a delay for showing optimistic update effect
    await new Promise((resolve) => setTimeout(resolve, 1000));
    return globalThis.fetch(url, init);
};

const clientQueries = useClientQueries(schema, { fetch, logging: true });
const { data: users, isFetched: isUsersFetched } = clientQueries.user.useFindMany();

const { data: posts } = clientQueries.post.useFindMany(
    () => ({
        where: showPublishedOnly.value ? { published: true } : undefined,
        orderBy: { createdAt: 'desc' },
        include: { author: true },
    }),
    () => ({ enabled: enableFetch.value }),
);

const createPost = clientQueries.post.useCreate(() => ({ optimisticUpdate: optimistic.value }));
const deletePost = clientQueries.post.useDelete(() => ({ optimisticUpdate: optimistic.value }));
const updatePost = clientQueries.post.useUpdate(() => ({ optimisticUpdate: optimistic.value }));

const onCreatePost = () => {
    if (!users.value) {
        return;
    }

    // random title
    const title = lorem.generateWords();

    // random user as author
    const forUser = users.value[Math.floor(Math.random() * users.value.length)]!;

    console.log('Creating post for user:', forUser.id, 'with title:', title);
    createPost.mutate({
        data: {
            title,
            authorId: forUser.id,
        },
    });
};

const onDeletePost = (postId: string) => {
    deletePost.mutate({
        where: { id: postId },
    });
};

const onTogglePublishPost = (post: Post) => {
    updatePost.mutate({
        where: { id: post.id },
        data: { published: !post.published },
    });
};
</script>

<template>
    <div v-if="isUsersFetched && (!users || users.length === 0)" class="p-4">
        No users found. Please run "pnpm db:init" to seed the database.
    </div>
    <div v-else class="flex min-h-screen items-center justify-center bg-zinc-50 font-sans dark:bg-black">
        <main
            class="flex min-h-screen w-full max-w-3xl flex-col items-center py-32 px-16 bg-white dark:bg-black sm:items-start"
        >
            <img src="/nuxt.svg" alt="Nuxt logo" width="100" height="20" />
            <div class="flex flex-col mt-8 items-center gap-6 text-center sm:items-start sm:text-left">
                <h1 class="max-w-xs text-3xl font-semibold leading-10 tracking-tight text-black dark:text-zinc-50">
                    My Awesome Blog
                </h1>

                <button
                    @click="onCreatePost"
                    class="rounded-md bg-blue-600 px-4 py-2 text-white hover:bg-blue-700 cursor-pointer"
                >
                    New Post
                </button>

                <div>
                    <div>Current users</div>
                    <div class="flex flex-col gap-1 p-2">
                        <div v-for="user in users" :key="user.id" class="text-sm text-gray-500">
                            {{ user.email }}
                        </div>
                    </div>
                </div>

                <div class="flex flex-col gap-1">
                    <label class="text-sm text-gray-700 dark:text-gray-300">
                        <input v-model="showPublishedOnly" type="checkbox" class="mr-2" />
                        Show published only
                    </label>

                    <label class="text-sm text-gray-700 dark:text-gray-300">
                        <input v-model="enableFetch" type="checkbox" class="mr-2" />
                        Enable fetch
                    </label>

                    <label class="text-sm text-gray-700 dark:text-gray-300">
                        <input v-model="optimistic" type="checkbox" class="mr-2" />
                        Optimistic update
                    </label>
                </div>

                <ul class="flex flex-col gap-2 container">
                    <li v-for="post in posts" :key="post.id">
                        <div class="flex justify-between">
                            <div class="flex gap-2 items-baseline">
                                <h2 class="text-xl font-semibold">{{ post.title }}</h2>
                                <span v-if="post.$optimistic" class="text-sm">pending</span>
                            </div>
                            <div class="ml-4 flex w-32">
                                <button
                                    class="rounded-md px-2 py-1 text-white cursor-pointer underline text-xs"
                                    @click="onDeletePost(post.id)"
                                >
                                    Delete
                                </button>
                                <button
                                    class="rounded-md px-2 py-1 text-white cursor-pointer underline text-xs"
                                    @click="onTogglePublishPost(post)"
                                >
                                    {{ post.published ? 'Unpublish' : 'Publish' }}
                                </button>
                            </div>
                        </div>
                        <p v-if="!post.$optimistic" class="text-sm text-gray-500">
                            by {{ post.author.name }} {{ !post.published ? '(Draft)' : '' }}
                        </p>
                    </li>
                </ul>
            </div>
        </main>
    </div>
</template>
